// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu8TMNvJEDITbLD1V_ap5dfr1u9M5v6Tc',
    appId: '1:359852956016:web:a9354dfc0891f2463cd7b5',
    messagingSenderId: '359852956016',
    projectId: 'firstfirebaseproj-c8266',
    authDomain: 'firstfirebaseproj-c8266.firebaseapp.com',
    storageBucket: 'firstfirebaseproj-c8266.appspot.com',
    measurementId: 'G-SVDQ0VY0DQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3WPyfxBP-hirk8JxHuhDYwFvwn-mvHlI',
    appId: '1:359852956016:android:8a18eefc2c9b49e43cd7b5',
    messagingSenderId: '359852956016',
    projectId: 'firstfirebaseproj-c8266',
    storageBucket: 'firstfirebaseproj-c8266.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKRb0amvgmwhqKWLp2iW2Sb_tK7D1jOWY',
    appId: '1:359852956016:ios:ff3ea4e74f6a417d3cd7b5',
    messagingSenderId: '359852956016',
    projectId: 'firstfirebaseproj-c8266',
    storageBucket: 'firstfirebaseproj-c8266.appspot.com',
    iosBundleId: 'com.example.flutterTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKRb0amvgmwhqKWLp2iW2Sb_tK7D1jOWY',
    appId: '1:359852956016:ios:ff3ea4e74f6a417d3cd7b5',
    messagingSenderId: '359852956016',
    projectId: 'firstfirebaseproj-c8266',
    storageBucket: 'firstfirebaseproj-c8266.appspot.com',
    iosBundleId: 'com.example.flutterTemplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu8TMNvJEDITbLD1V_ap5dfr1u9M5v6Tc',
    appId: '1:359852956016:web:c7aa891725d2de5e3cd7b5',
    messagingSenderId: '359852956016',
    projectId: 'firstfirebaseproj-c8266',
    authDomain: 'firstfirebaseproj-c8266.firebaseapp.com',
    storageBucket: 'firstfirebaseproj-c8266.appspot.com',
    measurementId: 'G-Z7DNV8KEE6',
  );
}
